# Generated by Django 5.1.7 on 2025-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_item',
        ),
        migrations.AddField(
            model_name='contain',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
