# Generated by Django 5.1.7 on 2025-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_price_item_contain_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contain',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
